---
driver:
  name: vagrant

provisioner:
  name: chef_zero
  attributes:
    rackspace_cloud_monitoring:
      cloud_credentials_username: <%= ENV['RACKSPACE_USERNAME'] %>
      cloud_credentials_api_key: <%= ENV['RACKSPACE_API_KEY']%>

platforms:
  - name: centos-6.5
    run_list:
    - recipe[yum]
  - name: ubuntu-12.04
    run_list:
    - recipe[apt]
  - name: ubuntu-14.04
    run_list:
    - recipe[apt]


suites:
  - name: default
    run_list:
      - recipe[rackspace_cloud_monitoring_service_test::default]
